var searchData=
[
  ['errnum',['errnum',['../classxtd_1_1crt__exception.html#aa92494634d48f1f4ab9bb8f8b8bf8d64',1,'xtd::crt_exception']]],
  ['exception',['exception',['../classxtd_1_1exception.html#a69be96d4b7c70ae1c1813f233bc39e0f',1,'xtd::exception::exception(const source_location &amp;Source, const std::string &amp;What)'],['../classxtd_1_1exception.html#a2c4a95bbe8734fbcf9ab4d36cf97e5b6',1,'xtd::exception::exception(const exception &amp;build_config)'],['../classxtd_1_1exception.html#a13c560ca3f82179f67fa947e9b51599a',1,'xtd::exception::exception(exception &amp;&amp;build_config)'],['../classxtd_1_1socket_1_1exception.html#a1953cd5f19156a3e9c2d590e1638c276',1,'xtd::socket::exception::exception(const source_location &amp;loc, const xtd::string &amp;swhat)'],['../classxtd_1_1socket_1_1exception.html#ac65ca55ac180f86d25a457e880bad0d3',1,'xtd::socket::exception::exception(const exception &amp;ex)'],['../classxtd_1_1socket_1_1exception.html#a49ac6617c3e3484d89de7c240cf7b758',1,'xtd::socket::exception::exception(exception &amp;&amp;ex)']]]
];
